version: '2'
services:
  connect-example:
    build: .
    image: "connect-example"
    working_dir: /tink-connect-example
    volumes:
      - ..:/tink-connect-example
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent:ro
    environment:
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BRANCH
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - CLIENT_SECRET
      - TINK_BINK_GCLOUD_SERVICE_ACCOUNT
