steps:
  - name: 'Build connect-example for production'
    command: |
        npm install --unsafe-perm
        cd client && npm install --unsafe-perm
        npm run build
        cd .. && buildkite-agent artifact upload "client/build/**/*"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: connect-example
      BUILDKITE_DOCKER_COMPOSE_FILE: .buildkite/connect-example.yml

  - wait

  - block: "Confirm"
    branches: master

  - name: 'Upload to AppEngine'
    command: |
        echo $TINK_BINK_GCLOUD_SERVICE_ACCOUNT | base64 --decode | gcloud auth activate-service-account --key-file=-;
        echo -e "\nenv_variables:\n  CLIENT_SECRET: \"$CLIENT_SECRET\"\n" >> app.yaml
        buildkite-agent artifact download "client/build/*" client
        gcloud app deploy --project bink-197114 --quiet
    branches: master
